spring:
  application:
    name: realTalk
  datasource:
    url: "jdbc:mysql://localhost:3307/realTalk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=tr&characterEncoding=UTF-8&characterSetResults=UTF-8"
    username: "appuser"
    password: app123
    driver-class-name: "com.mysql.cj.jdbc.Driver"
