spring:
  application:
    name: realTalk

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jackson:
    default-property-inclusion: non_null
    spring:
      jackson:
        datatype:
          datetime:
            write-dates-as-timestamps: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8080}

  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.chatBox.realTalk: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"