logging:
  level:
    root: DEBUG
    com.chatBox.realtalk: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  profiles: local
