-- ============================================================================
-- RealTalk - V1: Identity, user profile, OAuth, sessions and blocking
-- Target: MySQL 8.x / InnoDB / utf8mb4
--
-- Important:
-- 1. Flyway must connect to an existing database (realTalk_db).
-- 2. Do not add CREATE DATABASE, USE or FOREIGN_KEY_CHECKS here.
-- 3. public_id is a UUID generated by the application and stored as BINARY(16).
-- 4. id is the internal BIGINT key used by joins and foreign keys.
-- ============================================================================

CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id BINARY(16) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NULL,
    system_role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    email_verified_at DATETIME(6) NULL,
    last_login_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_system_role CHECK (
        system_role IN ('USER', 'ADMIN')
    ),
    CONSTRAINT chk_users_status CHECK (
        status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'PENDING_VERIFY')
    )
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_users_status_created
    ON users(status, created_at DESC, id DESC);

CREATE TABLE user_profiles (
    user_id BIGINT UNSIGNED NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    avatar_key VARCHAR(512) NULL,
    bio VARCHAR(500) NULL,
    last_seen_at DATETIME(6) NULL,
    last_seen_privacy VARCHAR(30) NOT NULL DEFAULT 'EVERYONE',
    online_status_privacy VARCHAR(30) NOT NULL DEFAULT 'EVERYONE',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,

    CONSTRAINT pk_user_profiles PRIMARY KEY (user_id),
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_user_profiles_last_seen_privacy CHECK (
        last_seen_privacy IN ('EVERYONE', 'CONTACTS', 'NOBODY')
    ),
    CONSTRAINT chk_user_profiles_online_privacy CHECK (
        online_status_privacy IN ('EVERYONE', 'CONTACTS', 'NOBODY')
    )
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE oauth_accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),

    CONSTRAINT pk_oauth_accounts PRIMARY KEY (id),
    CONSTRAINT uk_oauth_accounts_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_oauth_accounts_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_accounts_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_oauth_accounts_provider CHECK (
        provider IN ('GOOGLE', 'FACEBOOK')
    )
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE user_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id BINARY(16) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash BINARY(32) NOT NULL,
    device_id VARCHAR(100) NULL,
    device_name VARCHAR(255) NULL,
    device_type VARCHAR(50) NULL,
    user_agent VARCHAR(1000) NULL,
    ip_address VARCHAR(45) NULL,
    expires_at DATETIME(6) NOT NULL,
    last_used_at DATETIME(6) NULL,
    revoked_at DATETIME(6) NULL,
    revoke_reason VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
        ON UPDATE CURRENT_TIMESTAMP(6),

    CONSTRAINT pk_user_sessions PRIMARY KEY (id),
    CONSTRAINT uk_user_sessions_public_id UNIQUE (public_id),
    CONSTRAINT uk_user_sessions_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_user_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_user_sessions_user_active
    ON user_sessions(user_id, revoked_at, expires_at, id);

CREATE INDEX idx_user_sessions_expiration_cleanup
    ON user_sessions(expires_at, id);

CREATE TABLE user_blocks (
    blocker_user_id BIGINT UNSIGNED NOT NULL,
    blocked_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT pk_user_blocks
        PRIMARY KEY (blocker_user_id, blocked_user_id),
    CONSTRAINT fk_user_blocks_blocker
        FOREIGN KEY (blocker_user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_blocks_blocked
        FOREIGN KEY (blocked_user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_user_blocks_not_self CHECK (
        blocker_user_id <> blocked_user_id
    )
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_user_blocks_blocked
    ON user_blocks(blocked_user_id, blocker_user_id);
