spring:
  application:
    name: realTalk
  datasource:
    url: "jdbc:mysql://localhost:3307/realTalk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=tr&characterEncoding=UTF-8&characterSetResults=UTF-8"
    username: "appuser"
    password: app123
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQLDialect"
    properties:
      hibernate:
        connection:
          CharSet: "UTF-8"
          characterEncoding: "UTF-8"
          useUnicode: true
  spring doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
    logging:
      level:
        com.usermanagement: DEBUG
        org.springframework.data.elasticsearch: WARN
        org.elasticsearch.client: WARN